import type { AnalysisResult } from '../types/analysis';

export function generateMarkdown(result: AnalysisResult): string {
  const lines: string[] = [];

  lines.push('# Technology Stack Analysis');
  lines.push('');
  lines.push(`**URL:** ${result.url}`);
  lines.push(`**Analyzed:** ${new Date(result.analyzedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`);
  lines.push('');
  lines.push('## Executive Summary');
  lines.push('');
  lines.push(result.summary);
  lines.push('');

  // Main table
  lines.push('## Current Technology Stack');
  lines.push('');
  lines.push('| Category | Current Technology | Challenges & Pain Points |');
  lines.push('|----------|-------------------|--------------------------|');

  for (const cat of result.categories) {
    const tech = cat.currentTechnology.replace(/\|/g, '\\|');
    const challenges = cat.challengesAndPainPoints.replace(/\|/g, '\\|');
    lines.push(`| ${cat.category} | ${tech} | ${challenges} |`);
  }

  lines.push('');

  // Adobe opportunities
  const opportunities = result.categories.filter(
    (c) => c.adobeOpportunity && c.adobeOpportunity !== 'N/A' && c.adobeOpportunity !== '',
  );

  if (opportunities.length > 0) {
    lines.push('## Adobe Opportunities');
    lines.push('');
    for (const cat of opportunities) {
      lines.push(`### ${cat.category}`);
      lines.push(`- **Current:** ${cat.currentTechnology}`);
      lines.push(`- **Recommendation:** ${cat.adobeOpportunity}`);
      lines.push(`- **Pain Points:** ${cat.challengesAndPainPoints}`);
      lines.push('');
    }
  }

  // Raw detections
  if (result.rawDetections.length > 0) {
    lines.push('## Detected Technologies (Automated Scan)');
    lines.push('');
    for (const tech of result.rawDetections) {
      const version = tech.version ? ` v${tech.version}` : '';
      lines.push(`- **${tech.name}${version}** (${tech.categories.join(', ')}) — ${tech.confidence}% confidence`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by TechStack Analyzer*');

  return lines.join('\n');
}

export function downloadMarkdown(result: AnalysisResult) {
  const md = generateMarkdown(result);
  // Data-URL statt Blob – funktioniert auch über HTTP (kein "insecure blob" Fehler)
  const dataUrl = 'data:text/markdown;charset=utf-8,' + encodeURIComponent(md);
  const a = document.createElement('a');
  a.href = dataUrl;

  try {
    const hostname = new URL(result.url).hostname.replace(/\./g, '-');
    a.download = `techstack-${hostname}.md`;
  } catch {
    a.download = `techstack-analysis.md`;
  }

  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
}
